import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { LogOut, Package, Plus, Save, Settings, ShoppingBag, Truck } from 'lucide-react'
import { getAdminProducts, getAdminVariants, getEvents, getOrderItems, getOrders, getSettings, isAdmin } from './lib/api'
import { dateTime, money } from './lib/format'
import { supabase } from './lib/supabase'
import type { Order, OrderItem, Product, StoreSetting, TrackingEvent, Variant } from './types'

const message = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong.'
function AdminNotice({ children }: { children: ReactNode }) { return <p className="admin-notice">{children}</p> }
export function RequireAdmin({ children }: { children: ReactNode }) {
  const [state, setState] = useState<'loading' | 'allowed' | 'denied'>('loading')
  useEffect(() => { supabase.auth.getSession().then(async ({ data }) => { if (!data.session) return setState('denied'); try { setState(await isAdmin() ? 'allowed' : 'denied') } catch { setState('denied') } }) }, [])
  if (state === 'loading') return <p className="page-pad muted">Checking access...</p>
  return state === 'allowed' ? <>{children}</> : <Navigate to="/admin/login" replace />
}
export function AdminLogin() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setError(''); const { error: authError } = await supabase.auth.signInWithPassword({ email: String(form.get('email')), password: String(form.get('password')) }); if (authError) setError(authError.message); else { try { if (await isAdmin()) navigate('/admin'); else { await supabase.auth.signOut(); setError('This account is not an administrator.') } } catch (err) { setError(message(err)) } } setBusy(false) }
  return <main className="login-wrap"><form className="login-card" onSubmit={submit}><Link to="/" className="brand">NEXIST</Link><p className="eyebrow">Admin</p><h1>Welcome back</h1><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Password<input name="password" type="password" required autoComplete="current-password" /></label>{error && <AdminNotice>{error}</AdminNotice>}<button className="primary" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}</button></form></main>
}
function AdminShell({ children }: { children: ReactNode }) { const navigate = useNavigate(); async function logout() { await supabase.auth.signOut(); navigate('/admin/login') } return <div className="admin-shell"><aside className="admin-nav"><Link to="/" className="brand">NEXIST</Link><p>ADMINISTRATION</p><NavLink end to="/admin"><ShoppingBag size={17} /> Overview</NavLink><NavLink to="/admin/products"><Package size={17} /> Products</NavLink><NavLink to="/admin/orders"><Truck size={17} /> Orders</NavLink><NavLink to="/admin/settings"><Settings size={17} /> Settings</NavLink><button onClick={logout}><LogOut size={17} /> Sign out</button></aside><main className="admin-main">{children}</main></div> }
function Overview() { const [orders, setOrders] = useState<Order[]>([]); const [products, setProducts] = useState<Product[]>([]); useEffect(() => { getOrders().then(setOrders).catch(() => undefined); getAdminProducts().then(setProducts).catch(() => undefined) }, []); return <section><p className="eyebrow">Store overview</p><h1>Dashboard</h1><div className="stat-grid"><div><span>Orders</span><strong>{orders.length}</strong></div><div><span>Revenue</span><strong>{money(orders.reduce((sum, order) => sum + Number(order.total), 0))}</strong></div><div><span>Products</span><strong>{products.length}</strong></div></div><h2>Recent orders</h2><OrderTable orders={orders.slice(0, 6)} /></section> }
function ProductForm({ product, onSaved }: { product?: Product; onSaved: () => void }) { const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const payload = { name: String(form.get('name')), slug: String(form.get('slug')), description: String(form.get('description')), price: Number(form.get('price')), active: form.get('active') === 'on', image_url: String(form.get('image_url')) || null, category: String(form.get('category')) }; const query = product ? supabase.from('products').update(payload).eq('id', product.id) : supabase.from('products').insert(payload); const { error: saveError } = await query; if (saveError) setError(saveError.message); else onSaved() } return <form className="data-form" onSubmit={submit}><label>Name<input name="name" defaultValue={product?.name} required /></label><label>Slug<input name="slug" defaultValue={product?.slug} required /></label><label>Category<input name="category" defaultValue={product?.category} required /></label><label>Price<input name="price" type="number" min="0" step="0.001" defaultValue={product?.price} required /></label><label className="full">Image URL<input name="image_url" type="url" defaultValue={product?.image_url ?? ''} /></label><label className="full">Description<textarea name="description" defaultValue={product?.description} rows={3} required /></label><label className="check"><input name="active" type="checkbox" defaultChecked={product?.active ?? true} /> Active</label>{error && <AdminNotice>{error}</AdminNotice>}<button className="primary"><Save size={16} /> Save product</button></form> }
function Products() { const [products, setProducts] = useState<Product[]>([]); const [variants, setVariants] = useState<Variant[]>([]); const [editing, setEditing] = useState<Product | undefined>(); const [showNew, setShowNew] = useState(false); const [error, setError] = useState(''); const refresh = () => { getAdminProducts().then(setProducts).catch(e => setError(message(e))); getAdminVariants().then(setVariants).catch(e => setError(message(e))); setEditing(undefined); setShowNew(false) }; useEffect(() => { refresh() }, []); const selected = editing; return <section><div className="admin-title"><div><p className="eyebrow">Catalog</p><h1>Products</h1></div><button className="primary" onClick={() => setShowNew(true)}><Plus size={17} /> Add product</button></div>{error && <AdminNotice>{error}</AdminNotice>}{(showNew || selected) && <div className="editor"><h2>{selected ? `Edit ${selected.name}` : 'New product'}</h2><ProductForm product={selected} onSaved={refresh} /></div>}<div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th /></tr></thead><tbody>{products.map(product => <tr key={product.id}><td>{product.name}</td><td>{product.category}</td><td>{money(product.price)}</td><td>{variants.filter(v => v.product_id === product.id).reduce((sum, v) => sum + v.stock, 0)}</td><td>{product.active ? 'Active' : 'Hidden'}</td><td><button className="text-button" onClick={() => { setEditing(product); setShowNew(false) }}>Edit</button><VariantEditor product={product} variants={variants.filter(v => v.product_id === product.id)} onSaved={refresh} /></td></tr>)}</tbody></table></div></section> }
function VariantEditor({ product, variants, onSaved }: { product: Product; variants: Variant[]; onSaved: () => void }) { const [open, setOpen] = useState(false); const [error, setError] = useState(''); async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const id = String(form.get('id') || ''); const payload = { product_id: product.id, size: String(form.get('size')), stock: Number(form.get('stock')) }; const { error: saveError } = id ? await supabase.from('product_variants').update(payload).eq('id', id) : await supabase.from('product_variants').insert(payload); if (saveError) setError(saveError.message); else { onSaved(); setOpen(false) } } return <><button className="text-button" onClick={() => setOpen(!open)}>Stock</button>{open && <div className="variant-box"><h3>{product.name} sizes</h3>{variants.map(v => <form key={v.id} onSubmit={save}><input type="hidden" name="id" value={v.id} /><input name="size" defaultValue={v.size} required /><input name="stock" type="number" min="0" defaultValue={v.stock} required /><button aria-label="Save variant"><Save size={15} /></button></form>)}<form onSubmit={save}><input name="size" placeholder="New size" required /><input name="stock" type="number" min="0" placeholder="Stock" required /><button aria-label="Add variant"><Plus size={15} /></button></form>{error && <AdminNotice>{error}</AdminNotice>}</div>}</> }
function OrderTable({ orders, select }: { orders: Order[]; select?: (order: Order) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Created</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} onClick={() => select?.(order)} className={select ? 'clickable' : ''}><td>{order.order_number}</td><td>{order.customer_name}</td><td>{money(order.total)}</td><td><span className="status">{order.status}</span></td><td>{dateTime(order.created_at)}</td></tr>)}</tbody></table></div> }
function Orders() { const [orders, setOrders] = useState<Order[]>([]); const [selected, setSelected] = useState<Order | null>(null); const [items, setItems] = useState<OrderItem[]>([]); const [events, setEvents] = useState<TrackingEvent[]>([]); const [error, setError] = useState(''); const refresh = () => getOrders().then(setOrders).catch(e => setError(message(e))); useEffect(() => { void refresh() }, []); useEffect(() => { if (selected) { getOrderItems(selected.id).then(setItems).catch(e => setError(message(e))); getEvents(selected.id).then(setEvents).catch(e => setError(message(e))) } }, [selected]); async function updateStatus(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!selected) return; const status = String(new FormData(e.currentTarget).get('status')); const { error: updateError } = await supabase.from('orders').update({ status }).eq('id', selected.id); if (updateError) setError(updateError.message); else { const next = { ...selected, status }; setSelected(next); refresh() } } async function addEvent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!selected) return; const form = new FormData(e.currentTarget); const { error: insertError } = await supabase.from('tracking_events').insert({ order_id: selected.id, status: String(form.get('status')), note: String(form.get('note')) }); if (insertError) setError(insertError.message); else { e.currentTarget.reset(); getEvents(selected.id).then(setEvents) } } return <section><p className="eyebrow">Fulfilment</p><h1>Orders</h1>{error && <AdminNotice>{error}</AdminNotice>}<OrderTable orders={orders} select={setSelected} />{selected && <div className="editor"><h2>{selected.order_number}</h2><p>{selected.customer_name} · {selected.phone}<br />{selected.address}, {selected.delegation}, {selected.governorate}</p><form className="inline-form" onSubmit={updateStatus}><select name="status" defaultValue={selected.status}><option>Pending</option><option>Confirmed</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select><button className="primary">Update status</button></form><h3>Items</h3>{items.map(item => <p key={item.id}>{item.product_name} / {item.size} x{item.quantity} <strong>{money(item.subtotal)}</strong></p>)}<h3>Tracking events</h3>{events.map(event => <p key={event.id}><strong>{event.status}</strong> {event.note} <span className="muted">{dateTime(event.created_at)}</span></p>)}<form className="event-form" onSubmit={addEvent}><input name="status" placeholder="Status" required /><input name="note" placeholder="Customer-facing note" required /><button className="primary">Add event</button></form></div>}</section> }
function SettingsPage() { const [settings, setSettings] = useState<StoreSetting[]>([]); const [error, setError] = useState(''); const refresh = () => getSettings().then(setSettings).catch(e => setError(message(e))); useEffect(() => { void refresh() }, []); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const payload = settings.map(setting => ({ key: setting.key, value: String(form.get(setting.key)) })); const { error: saveError } = await supabase.from('store_settings').upsert(payload); if (saveError) setError(saveError.message); else refresh() } return <section><p className="eyebrow">Configuration</p><h1>Store settings</h1><p className="muted">Only settings exposed by the existing policy are shown.</p>{error && <AdminNotice>{error}</AdminNotice>}<form className="settings-form" onSubmit={submit}>{settings.map(setting => <label key={setting.key}>{setting.key}<input name={setting.key} defaultValue={setting.value} required /></label>)}<button className="primary"><Save size={16} /> Save settings</button></form></section> }
export function AdminPanel() { return <AdminShell><Routes><Route index element={<Overview />} /><Route path="products" element={<Products />} /><Route path="orders" element={<Orders />} /><Route path="settings" element={<SettingsPage />} /></Routes></AdminShell> }
