import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Check, ChevronRight, Minus, Package, Plus, Search, ShoppingBag, UserRound } from 'lucide-react'
import { checkout, getProduct, getProducts, getPublicTracking, getVariants } from './lib/api'
import { dateTime, money } from './lib/format'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import { useCart } from './state/cart'
import type { CheckoutResult, Product, PublicTracking, Variant } from './types'
import { AdminLogin, AdminPanel, RequireAdmin } from './admin'

function Notice({ children }: { children: ReactNode }) { return <div className="notice">{children}</div> }
function Loading() { return <p className="muted page-pad">Loading...</p> }
function Image({ product }: { product: Product }) { return product.image_url ? <img className="product-image" src={product.image_url} alt={product.name} /> : <div className="image-placeholder"><Package size={34} /></div> }

function Header() {
  const { count } = useCart()
  return <header className="site-header"><Link to="/" className="brand">NEXIST</Link><nav><NavLink to="/track">Track order</NavLink><NavLink to="/admin/login" aria-label="Admin login"><UserRound size={18} /></NavLink><NavLink to="/cart" className="cart-link" aria-label="Cart"><ShoppingBag size={19} /><span>{count}</span></NavLink></nav></header>
}
function Storefront() {
  const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState('')
  useEffect(() => { getProducts().then(setProducts).catch(e => setError(e.message)) }, [])
  const categories = [...new Set(products.map(product => product.category).filter(Boolean))]
  return <><section className="store-intro"><p className="eyebrow">Tunisian essentials</p><h1>Made for the present.</h1><p>Everyday pieces, considered down to the last detail.</p></section><main className="page-pad"><div className="collection-heading"><div><p className="eyebrow">Collection</p><h2>Available now</h2></div><span>{products.length} pieces</span></div>{categories.length > 0 && <div className="categories">{categories.map(category => <span key={category}>{category}</span>)}</div>}{error && <Notice>{error}</Notice>}{!error && products.length === 0 ? <Loading /> : <div className="product-grid">{products.map(product => <Link className="product-card" key={product.id} to={`/products/${product.slug}`}><Image product={product} /><div><span className="category">{product.category}</span><h3>{product.name}</h3><strong>{money(product.price)}</strong></div></Link>)}</div>}</main></>
}
function ProductPage() {
  const { slug = '' } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [variants, setVariants] = useState<Variant[]>([]); const [selected, setSelected] = useState<Variant | null>(null); const [quantity, setQuantity] = useState(1); const [error, setError] = useState(''); const { add } = useCart(); const navigate = useNavigate()
  useEffect(() => { getProduct(slug).then(p => { setProduct(p); return getVariants(p.id) }).then(v => { setVariants(v); setSelected(v.find(x => x.stock > 0) ?? null) }).catch(e => setError(e.message)) }, [slug])
  if (error) return <main className="page-pad"><Notice>{error}</Notice></main>; if (!product) return <Loading />
  const max = selected?.stock ?? 0
  return <main className="product-detail page-pad"><Link to="/" className="back"><ArrowLeft size={17} /> Shop</Link><Image product={product} /><section className="product-info"><span className="category">{product.category}</span><h1>{product.name}</h1><strong className="price">{money(product.price)}</strong><p>{product.description}</p><fieldset><legend>Size</legend><div className="size-picker">{variants.map(variant => <button type="button" key={variant.id} disabled={variant.stock < 1} aria-pressed={selected?.id === variant.id} onClick={() => { setSelected(variant); setQuantity(1) }}>{variant.size}<small>{variant.stock > 0 ? `${variant.stock} left` : 'Sold out'}</small></button>)}</div></fieldset><div className="purchase-row"><div className="stepper"><button aria-label="Decrease quantity" onClick={() => setQuantity(q => Math.max(1, q - 1))}><Minus size={15} /></button><span>{quantity}</span><button aria-label="Increase quantity" disabled={quantity >= max} onClick={() => setQuantity(q => Math.min(max, q + 1))}><Plus size={15} /></button></div><button className="primary" disabled={!selected} onClick={() => { if (selected) { add(product, selected, quantity); navigate('/cart') } }}>Add to cart</button></div></section></main>
}
function Cart() { const { items, subtotal, update, remove } = useCart(); return <main className="page-pad narrow"><h1>Your cart</h1>{items.length === 0 ? <div className="empty"><ShoppingBag size={32} /><p>Your cart is waiting.</p><Link className="primary" to="/">Browse collection</Link></div> : <><div className="cart-list">{items.map(item => <article className="cart-item" key={item.variant.id}><Image product={item.product} /><div><h3>{item.product.name}</h3><p>{item.variant.size}</p><strong>{money(item.product.price)}</strong></div><div className="cart-actions"><div className="stepper"><button aria-label="Decrease quantity" onClick={() => update(item.variant.id, item.quantity - 1)}><Minus size={14} /></button><span>{item.quantity}</span><button aria-label="Increase quantity" disabled={item.quantity >= item.variant.stock} onClick={() => update(item.variant.id, item.quantity + 1)}><Plus size={14} /></button></div><button className="text-button" onClick={() => remove(item.variant.id)}>Remove</button></div></article>)}</div><div className="total-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><Link to="/checkout" className="primary wide">Checkout <ChevronRight size={18} /></Link></>}</main> }
function Checkout() {
  const { items, subtotal, clear } = useCart(); const nav = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!items.length) return; setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { const result = await checkout({ customer_name: String(form.get('customer_name')), phone: String(form.get('phone')), governorate: String(form.get('governorate')), delegation: String(form.get('delegation')), address: String(form.get('address')), notes: String(form.get('notes')), items: items.map(item => ({ product_id: item.product.id, size: item.variant.size, quantity: item.quantity })) }); clear(); sessionStorage.setItem('nexist-checkout', JSON.stringify(result)); nav('/confirmation') } catch (e) { setError(e instanceof Error ? e.message : 'Could not place your order.') } finally { setBusy(false) } }
  if (!items.length) return <Navigate to="/cart" replace />
  return <main className="page-pad checkout"><div><Link to="/cart" className="back"><ArrowLeft size={17} /> Cart</Link><h1>Delivery details</h1><form onSubmit={submit} className="form-grid"><label>Full name<input name="customer_name" required /></label><label>Phone<input name="phone" type="tel" required /></label><label>Governorate<input name="governorate" required /></label><label>Delegation<input name="delegation" required /></label><label className="full">Address<textarea name="address" required rows={3} /></label><label className="full">Order notes <span className="muted">(optional)</span><textarea name="notes" rows={2} /></label>{error && <Notice>{error}</Notice>}<button className="primary" disabled={busy}>{busy ? 'Placing order...' : 'Place order'}</button></form></div><aside className="order-summary"><h2>Order summary</h2>{items.map(item => <p key={item.variant.id}><span>{item.product.name} / {item.variant.size} x{item.quantity}</span><strong>{money(item.product.price * item.quantity)}</strong></p>)}<div className="total-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><small>Delivery is calculated securely at checkout.</small></aside></main>
}
function Confirmation() { const raw = sessionStorage.getItem('nexist-checkout'); const result = raw ? JSON.parse(raw) as CheckoutResult : null; if (!result) return <Navigate to="/" replace />; return <main className="page-pad narrow confirmation"><div className="success-icon"><Check size={28} /></div><p className="eyebrow">Order placed</p><h1>Thank you.</h1><p>Order <strong>{result.order_number}</strong> is confirmed. Total: <strong>{money(result.total)}</strong>.</p>{result.estimated_delivery && <p>Estimated delivery: {result.estimated_delivery}</p>}<Link className="primary" to={`/track?token=${encodeURIComponent(result.tracking_token)}`}>Track your order</Link></main> }
function Track() { const [token, setToken] = useState(new URLSearchParams(location.search).get('token') ?? ''); const [tracking, setTracking] = useState<PublicTracking | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function lookup(event?: FormEvent<HTMLFormElement>) { event?.preventDefault(); const value = token.trim(); if (!value) return; setBusy(true); setError(''); setTracking(null); try { const result = await getPublicTracking(value); setTracking(result); window.history.replaceState(null, '', `/track?token=${encodeURIComponent(value)}`) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to retrieve this order.') } finally { setBusy(false) } } useEffect(() => { if (token) void lookup() }, []); return <main className="page-pad narrow track"><p className="eyebrow">Order status</p><h1>Track your order</h1><p>Enter the tracking token from your order confirmation.</p><form onSubmit={lookup}><label>Tracking token<input value={token} onChange={event => setToken(event.target.value)} required /></label><button className="primary" type="submit" disabled={busy}><Search size={17} /> {busy ? 'Checking...' : 'Track order'}</button></form>{error && <Notice>{error}</Notice>}{tracking && <section className="order-summary"><p><span>Order</span><strong>{tracking.order_number}</strong></p><p><span>Status</span><strong>{tracking.status}</strong></p><p><span>Total</span><strong>{money(tracking.total)}</strong></p><p><span>Placed</span><strong>{dateTime(tracking.created_at)}</strong></p>{tracking.estimated_delivery && <p><span>Estimated delivery</span><strong>{tracking.estimated_delivery}</strong></p>}<h2>Tracking updates</h2>{tracking.tracking_events.length === 0 ? <p className="muted">No tracking updates yet.</p> : tracking.tracking_events.map(event => <p key={`${event.created_at}-${event.status}`}><span><strong>{event.status}</strong><br />{event.note}</span><strong>{dateTime(event.created_at)}</strong></p>)}</section>}</main> }
export function App() { return <><Header />{!isSupabaseConfigured && <Notice>Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable the store.</Notice>}<Routes><Route path="/" element={<Storefront />} /><Route path="/products/:slug" element={<ProductPage />} /><Route path="/cart" element={<Cart />} /><Route path="/checkout" element={<Checkout />} /><Route path="/confirmation" element={<Confirmation />} /><Route path="/track" element={<Track />} /><Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin/*" element={<RequireAdmin><AdminPanel /></RequireAdmin>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></> }
